In [1]:
import numpy as np


# 1 dimensional array

In [2]:
a=[]
n=int(input("enter list capacity "))

for i in range(n):
    c=int(input("Enter number"))
    a.append(c)

array=np.array(a)
print(array)

enter list capacity 5
Enter number11
Enter number22
Enter number33
Enter number44
Enter number55
[11 22 33 44 55]


In [4]:
print(array)

[11 22 33 44 55]


In [5]:
# how to check dimensional 
array.ndim

1

In [7]:
# how to check shape
array.shape

(5,)

In [8]:
# how to check size in array
print(array.itemsize)
print(array.size)

4
5


# zeros

In [9]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [11]:
np.zeros((5,5),dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

# ones function

In [12]:
np.ones(5,dtype=int)

array([1, 1, 1, 1, 1])

In [13]:

np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
# asymmetrics metrics
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

# eye

In [22]:
# symmetrics metrics  no of column equel to number of rows
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# diag

In [23]:
np.diag((1,2,3,4))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [24]:
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

# random.randint

In [32]:
# np.random.randint ka use kiya jaya givan range ke according random number print karvata he 

np.random.randint(5,10,5)

array([6, 6, 5, 9, 9])

# random.rand

In [34]:
np.random.rand(5,5)

array([[0.38469547, 0.06380082, 0.34737222, 0.14257262, 0.93130437],
       [0.59515704, 0.03235443, 0.05248477, 0.12598949, 0.96906452],
       [0.41690986, 0.4035957 , 0.86473198, 0.32461922, 0.75452049],
       [0.03479921, 0.34867449, 0.3733309 , 0.72976598, 0.07629249],
       [0.76444758, 0.37883672, 0.82950475, 0.08742333, 0.52798858]])

# random.randn

In [35]:
array=np.random.randn(5,5)
print(array)

[[ 0.27496207  1.17786695  0.51500836  0.7445339   0.81216853]
 [-0.63731815  0.48799792  0.33638824  1.58218726 -1.14439071]
 [ 1.34807337  1.95630574 -0.88411339 -0.61272658 -0.59727501]
 [-1.70891617 -0.54755227 -0.89693956 -0.56404118 -0.54941208]
 [ 0.49086855 -1.14042018  1.37229795 -1.6368081   0.1534028 ]]


# reshape array

In [36]:
# number of column multiply number of rows equel to total number of element

In [37]:
array=np.random.randint(1,100,36)

In [38]:
array.reshape((1,36))

array([[49, 69, 69, 76, 78, 74, 48, 16, 30, 84, 10, 12, 90, 69, 63, 48,
        36, 45,  2, 32, 90, 24, 42, 46, 55, 42, 25, 51, 40, 96, 58, 59,
        22, 85, 74, 20]])

In [40]:
# array.reshape(36,1)

In [41]:
array.reshape(12,3)

array([[49, 69, 69],
       [76, 78, 74],
       [48, 16, 30],
       [84, 10, 12],
       [90, 69, 63],
       [48, 36, 45],
       [ 2, 32, 90],
       [24, 42, 46],
       [55, 42, 25],
       [51, 40, 96],
       [58, 59, 22],
       [85, 74, 20]])

In [42]:
array.reshape(18,2)

array([[49, 69],
       [69, 76],
       [78, 74],
       [48, 16],
       [30, 84],
       [10, 12],
       [90, 69],
       [63, 48],
       [36, 45],
       [ 2, 32],
       [90, 24],
       [42, 46],
       [55, 42],
       [25, 51],
       [40, 96],
       [58, 59],
       [22, 85],
       [74, 20]])

In [43]:
array.reshape(2,18)

array([[49, 69, 69, 76, 78, 74, 48, 16, 30, 84, 10, 12, 90, 69, 63, 48,
        36, 45],
       [ 2, 32, 90, 24, 42, 46, 55, 42, 25, 51, 40, 96, 58, 59, 22, 85,
        74, 20]])

# principal of -1

In [44]:
array.reshape(4,-1)

array([[49, 69, 69, 76, 78, 74, 48, 16, 30],
       [84, 10, 12, 90, 69, 63, 48, 36, 45],
       [ 2, 32, 90, 24, 42, 46, 55, 42, 25],
       [51, 40, 96, 58, 59, 22, 85, 74, 20]])

#  seed

In [47]:
np.random.seed(12)
np.random.randint(1,10,5)

array([7, 2, 3, 4, 4])

# view and Copy

In [49]:
# view me original data update ho jata he 
a=np.random.randint(1,10,10)
b=a[5:8]
b[:]=0
print(a)

[3 4 5 4 2 0 0 0 7 3]


In [50]:
# copy me original data update  nahi hota he 
a=np.random.randint(1,10,10)
b=a[5:8].copy()
b[:]=0
print(a)

[1 5 7 1 1 9 7 2 9 5]


# conditional selection 

In [53]:
a=np.arange(1,16)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [55]:
a[a>10]

array([11, 12, 13, 14, 15])

In [56]:
a[a==10]

array([10])

In [57]:
a[a%2==0]

array([ 2,  4,  6,  8, 10, 12, 14])

In [58]:
a[a%2!=0]

array([ 1,  3,  5,  7,  9, 11, 13, 15])

In [59]:
a*2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [60]:
a**2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225])

In [65]:
a=np.arange(1,5).reshape(2,2)
b=a*2
print(a)
print(b)

[[1 2]
 [3 4]]
[[2 4]
 [6 8]]


In [68]:
d=a+b

In [70]:
print(d)

[[ 3  6]
 [ 9 12]]


In [67]:
c=np.arange(1,3)
c

array([1, 2])

In [69]:

d+c

array([[ 4,  8],
       [10, 14]])

# other important function



In [71]:
a=np.array([10,20,30,40])

In [72]:
a.argmin()

0

In [73]:
a.argmax()

3

#  linspace

In [74]:
np.linspace(1,2,5)

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

# unique function

In [75]:
a=np.array([10,20,30,40,50,60])

In [76]:
np.unique(a,return_index=True,return_counts=True)

(array([10, 20, 30, 40, 50, 60]),
 array([0, 1, 2, 3, 4, 5], dtype=int64),
 array([1, 1, 1, 1, 1, 1], dtype=int64))

# horizontal and vertical stacking

In [79]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])

In [83]:
np.hsplit((a,b))

TypeError: _hvdsplit_dispatcher() missing 1 required positional argument: 'indices_or_sections'